/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SystemGUI;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

/**
 *
 * @author hunter
 */
public class CredentialFrame extends javax.swing.JFrame {
    /**
     * Creates new form Log
     */
    public CredentialFrame() {
        FlatMacDarkLaf.setup();
        initComponents();
        //header style(icon&title)
        //SVG - Scalable Victor Graphics
        FlatSVGIcon headerIcon = new FlatSVGIcon("SystemImgBgs/headerIcon.svg");
        setFont(new Font("Agency FB", 1, 20));
        setTitle("SAMS");
        setIconImage(headerIcon.getImage());
        
        initLoginPanelComponents();
        initSignupPanelComponents();
    }
    
    private void initLoginPanelComponents(){
        //UsernameTextField styling
        loginUsnmTF.putClientProperty("JComponent.roundRect", true);
        loginUsnmTF.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Username");
        loginUsnmTF.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON,new FlatSVGIcon("SystemImgBgs/usnmIcon.svg"));
        loginUsnmTF.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON,true);
        
        //PasswordField styling
        loginPwdF.putClientProperty("JComponent.roundRect", true);
        loginPwdF.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Password");
        loginPwdF.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON,new FlatSVGIcon("SystemImgBgs/pwdIcon.svg"));
        loginPwdF.putClientProperty(FlatClientProperties.STYLE, "showRevealButton:true");
        loginPwdF.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON,true);
        
        loginInnerFrame.putClientProperty("JComponent.roundRect", true);
        
        //LogoutButton icon
        loginBtn.setIcon(new FlatSVGIcon("SystemImgBgs/loginIcon.svg"));
    }
    
    private void initSignupPanelComponents(){
        //UsernameTextField styling
        signupUsnmTF.putClientProperty("JComponent.roundRect", true);
        signupUsnmTF.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Username");
        signupUsnmTF.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON,new FlatSVGIcon("SystemImgBgs/usnmIcon.svg"));
        signupUsnmTF.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON,true);
        
        //PasswordField styling
        signupPwdF.putClientProperty("JComponent.roundRect", true);
        signupPwdF.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Password");
        signupPwdF.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON,new FlatSVGIcon("SystemImgBgs/pwdIcon.svg"));
        signupPwdF.putClientProperty(FlatClientProperties.STYLE, "showRevealButton:true");
        signupPwdF.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON,true);
        
        signUpBtn.putClientProperty("JComponent.roundRect", true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CredentialPanels = new javax.swing.JTabbedPane();
        loginPanel = new javax.swing.JPanel();
        loginInnerFrame = new javax.swing.JPanel();
        loginUsnmTF = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        loginPwdF = new javax.swing.JPasswordField();
        headerLabel = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        AcntCreationLabel = new javax.swing.JLabel();
        loginBgLabel = new javax.swing.JLabel();
        signupPanel = new javax.swing.JPanel();
        signupInnerPanel = new javax.swing.JPanel();
        signupUsnmTF = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        signupPwdF = new javax.swing.JPasswordField();
        headerLabel1 = new javax.swing.JLabel();
        signUpBtn = new javax.swing.JButton();
        loginBgLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginInnerFrame.setBackground(new java.awt.Color(43, 75, 130));
        loginInnerFrame.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(102, 102, 255)));

        loginUsnmTF.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        loginUsnmTF.setForeground(new java.awt.Color(255, 255, 255));
        loginUsnmTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginUsnmTFKeyPressed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        loginPwdF.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        loginPwdF.setForeground(new java.awt.Color(255, 255, 255));
        loginPwdF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginPwdFKeyPressed(evt);
            }
        });

        headerLabel.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("ADMINISTRATOR");
        headerLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        loginBtn.setBackground(new java.awt.Color(51, 51, 51));
        loginBtn.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("LOGIN");

        AcntCreationLabel.setBackground(new java.awt.Color(255, 255, 255));
        AcntCreationLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AcntCreationLabel.setForeground(new java.awt.Color(255, 255, 255));
        AcntCreationLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AcntCreationLabel.setText("Don't Have an Account?");
        AcntCreationLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AcntCreationLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AcntCreationLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout loginInnerFrameLayout = new javax.swing.GroupLayout(loginInnerFrame);
        loginInnerFrame.setLayout(loginInnerFrameLayout);
        loginInnerFrameLayout.setHorizontalGroup(
            loginInnerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginInnerFrameLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginInnerFrameLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(loginInnerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginInnerFrameLayout.createSequentialGroup()
                        .addGroup(loginInnerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AcntCreationLabel)
                            .addComponent(loginUsnmTF, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginPwdF, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginInnerFrameLayout.createSequentialGroup()
                        .addComponent(headerLabel)
                        .addGap(104, 104, 104))))
        );
        loginInnerFrameLayout.setVerticalGroup(
            loginInnerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginInnerFrameLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(headerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(loginUsnmTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginPwdF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(AcntCreationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        loginPanel.add(loginInnerFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 350, 410));

        loginBgLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loginBgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemImgBgs/loginBg.png"))); // NOI18N
        loginPanel.add(loginBgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 760, 470));

        CredentialPanels.addTab("LoginF", loginPanel);

        signupPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signupInnerPanel.setBackground(new java.awt.Color(43, 75, 130));
        signupInnerPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(102, 102, 255)));

        signupUsnmTF.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        signupUsnmTF.setForeground(new java.awt.Color(255, 255, 255));
        signupUsnmTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                signupUsnmTFKeyPressed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        signupPwdF.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        signupPwdF.setForeground(new java.awt.Color(255, 255, 255));
        signupPwdF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                signupPwdFKeyPressed(evt);
            }
        });

        headerLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        headerLabel1.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel1.setText("ACCOUNT CREATION");
        headerLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        signUpBtn.setBackground(new java.awt.Color(51, 51, 51));
        signUpBtn.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        signUpBtn.setForeground(new java.awt.Color(255, 255, 255));
        signUpBtn.setText("SIGNUP");

        javax.swing.GroupLayout signupInnerPanelLayout = new javax.swing.GroupLayout(signupInnerPanel);
        signupInnerPanel.setLayout(signupInnerPanelLayout);
        signupInnerPanelLayout.setHorizontalGroup(
            signupInnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signupInnerPanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(signupInnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(signupUsnmTF, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signupPwdF, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(signupInnerPanelLayout.createSequentialGroup()
                .addGroup(signupInnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signupInnerPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(signUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signupInnerPanelLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(headerLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signupInnerPanelLayout.setVerticalGroup(
            signupInnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signupInnerPanelLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(headerLabel1)
                .addGap(52, 52, 52)
                .addComponent(signupUsnmTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signupPwdF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        signupPanel.add(signupInnerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 350, 410));

        loginBgLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loginBgLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemImgBgs/loginBg.png"))); // NOI18N
        signupPanel.add(loginBgLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 760, 470));

        CredentialPanels.addTab("SignupF", signupPanel);

        getContentPane().add(CredentialPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 760, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginPwdFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginPwdFKeyPressed
        if(Character.isLetterOrDigit(evt.getKeyCode())|| evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_SHIFT || evt.getExtendedKeyCode()==KeyEvent.VK_CAPS_LOCK){
            if(String.valueOf(loginPwdF.getPassword()).length()>=9){
                if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE) {
                    loginPwdF.putClientProperty("JComponent.outline","success");
                    loginPwdF.setEditable(true);
                }else{
                    loginPwdF.putClientProperty("JComponent.outline","error");
                    loginPwdF.setEditable(false);
                }
            }else{
                loginPwdF.setEditable(true);
                loginPwdF.putClientProperty("JComponent.outline","success");
            }
        }else{
            loginPwdF.setEditable(false);
            loginPwdF.putClientProperty("JComponent.outline","error");
        }
    }//GEN-LAST:event_loginPwdFKeyPressed

    private void AcntCreationLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcntCreationLabelMouseEntered
        // assigned a string that contains HTML formatting
        //It's creating a hyperlink-like appearance with an underlined text
        //So that outputted text would look like a hyperlink,
        //and the underlined text would imply that it is clickable or interactive.
        String text = "<HTML><u>Don't Have an Account?</u></HTML>";
        AcntCreationLabel.setText(text);
    }//GEN-LAST:event_AcntCreationLabelMouseEntered

    private void AcntCreationLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcntCreationLabelMouseExited
        AcntCreationLabel.setText("Don't Have an Account?");
    }//GEN-LAST:event_AcntCreationLabelMouseExited

    private void signupPwdFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signupPwdFKeyPressed
        if(Character.isLetterOrDigit(evt.getKeyCode())|| evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_SHIFT || evt.getExtendedKeyCode()==KeyEvent.VK_CAPS_LOCK){
            if(String.valueOf(signupPwdF.getPassword()).length()>=9){
                if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE) {
                    signupPwdF.putClientProperty("JComponent.outline","success");
                    signupPwdF.setEditable(true);
                }else{
                    signupPwdF.putClientProperty("JComponent.outline","error");
                    signupPwdF.setEditable(false);
                }
            }else{
                signupPwdF.setEditable(true);
                signupPwdF.putClientProperty("JComponent.outline","success");
            }
        }else{
            signupPwdF.setEditable(false);
            signupPwdF.putClientProperty("JComponent.outline","error");
        }
    }//GEN-LAST:event_signupPwdFKeyPressed

    private void loginUsnmTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginUsnmTFKeyPressed
       if(loginUsnmTF.getText().length()>=0){
           loginUsnmTF.putClientProperty("JComponent.outline","success");
       }
    }//GEN-LAST:event_loginUsnmTFKeyPressed

    private void signupUsnmTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signupUsnmTFKeyPressed
        if(signupUsnmTF.getText().length()>=0){
           signupUsnmTF.putClientProperty("JComponent.outline","success");
       }
    }//GEN-LAST:event_signupUsnmTFKeyPressed
    
    /* All the methods below are used in the controller class (Main Class)*/
    public JTabbedPane getCredentialPanels(){
        return CredentialPanels;
    }
    //Login Panel from Tabbed Pane
    public JLabel getAccountCreationLabelFunction(){
        return AcntCreationLabel;
    }
    
    public JButton getLoginBtnFunction(){
      return loginBtn;
    }
    
    public JTextField getLoginUsnmTF(){
        return loginUsnmTF;
    }
    
    public JPasswordField getLoginPwdF(){
        return loginPwdF;
    }
    
    //SignUp Panel from Tabbed Pane
    public JButton getSignUpBtnFunction(){
        return signUpBtn;
    }
    
    public JTextField getSignupUsnmTF(){
        return signupUsnmTF;
    }
    
    public JPasswordField getSignupPwdF(){
        return signupPwdF;
    }
    /*-------------------------------------*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AcntCreationLabel;
    private javax.swing.JTabbedPane CredentialPanels;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel headerLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel loginBgLabel;
    private javax.swing.JLabel loginBgLabel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginInnerFrame;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField loginPwdF;
    private javax.swing.JTextField loginUsnmTF;
    private javax.swing.JButton signUpBtn;
    private javax.swing.JPanel signupInnerPanel;
    private javax.swing.JPanel signupPanel;
    private javax.swing.JPasswordField signupPwdF;
    private javax.swing.JTextField signupUsnmTF;
    // End of variables declaration//GEN-END:variables

}
